construct {
    ?o rdfs:label ?name ;
        tmp:parent ?parent .
    ?parent rdfs:label ?parentName ;
        tmp:child ?o .
}
where {
    ?o a foaf:Organization ;
        rdfs:label ?name ;
         obo:BFO_0000050 ?parent .
    ?parent rdfs:label ?parentName .
}
