construct {
    ?p a tmp:Person ;
        rdfs:label ?name ;
        tmp:pic ?picture ;
        tmp:description ?desc ;
        tmp:position ?position .
    ?position rdfs:label ?title ;
	tmp:rank ?rank ;
        tmp:org ?org.
    ?org rdfs:label ?orgName .
}
where {
    ?p a foaf:Person ;
        rdfs:label ?name ;
        fhd:sortLetter ?startswith ;
        vivo:relatedBy ?position .
    OPTIONAL {?p fhd:image ?picture }
    OPTIONAL {?p fhd:briefDescription ?desc }
    ?position a vivo:Position ;
            rdfs:label ?title ;
	    vivo:rank ?rank ;
            vivo:relates ?org .
    ?org a foaf:Organization ;
         rdfs:label ?orgName .
}
