select distinct ?link ?label ?url
where {
    ?person tmp:link ?link .
    ?link rdfs:label ?label ;
          tmp:url ?url .
    FILTER  (regex(?label, "group", "i") || regex(?label, "initiative", "i") || 
    regex(?label, "institute", "i") || regex(?label, "lab", "i") || 
    regex(?label, "program", "i")) || regex(?label, "studies", "i")
}
