select distinct ?title ?org ?orgName ?parentOrgName
where {
    ?person rdfs:label ?name ;
        tmp:position ?position .
    ?position rdfs:label ?title ;
	    tmp:rank ?rank ;
            tmp:org ?org .
    ?org rdfs:label ?orgName .
    OPTIONAL {
        ?org tmp:parent ?parentOrg .
        ?parentOrg rdfs:label ?parentOrgName .
    }
}
ORDER BY ?rank ?orgName
